name: Run tests

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      - devel

jobs:
  run:
    name: test with pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt-get install libmecab2 mecab mecab-ipadic sqlite3 libboost-dev libboost-all-dev libboost-regex-dev libmecab-dev libsqlite3-dev build-essential -y
          python3 -m pip install --upgrade pip
          python3 -m　pip install --break-system-packages pytest
          python3 -m　pip install --break-system-packages -r requirements.txt
          python3 -m　pip install --break-system-packages git+https://github.com/searxng/searxng
          python3 -m pygeonlp.api setup /usr/pygeonlp_basedata
      - name: Run test
        run: |
          pytest