name: Run tests
on:
  workflow_dispatch:
  push:
    branches:
      - *
jobs:
  run:
    name: test with pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt-get install libmecab2 mecab mecab-ipadic sqlite3 libboost-dev libboost-all-dev libboost-regex-dev libmecab-dev libsqlite3-dev build-essential -y
          python -m pip install --upgrade pip
          pip install --break-system-packages pytest
          pip install --break-system-packages -r requirements.txt
          python3 -m pygeonlp.api setup /usr/pygeonlp_basedata
      - name: Run test
        run: |
          pytest